### ISSUE TITLE
"RuntimeError: CUDA error: device-side assert triggered" for attacking SNLI BERT.

### ISSUE THREAD

**Issue by ashim95** [dugu9sword/dne#1]
Hi,

Thanks for releasing the code with your paper. 

I am trying to reproduce your results for SNLI BERT model, and I am getting the following error:

```
Load checkpoint at 2, with validation_accuracy=0.8939
Load model from saved/models/SNLI-wbert-1.0-64-2nd-0.5-diy.3.10.0/model_state_epoch_2.th
The metric at epoch 2 is: [('training_accuracy', 0.861118594580229), ('validation_accuracy', 0.8939024390243903), ('best_validation_accuracy', 0.8939024390243903)]
Downsample 500 samples at shard 0 on dev set
  0%|                                                                                                                                                        | 0/8 [00:00<?, ?it/s]The weighted embedding is working
INFO: check the flag warm_mode=False, the information only occurs once.
INFO: check the flag weighted_off=False, the information only occurs once.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [524,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [524,0,0], thread: [33,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [524,0,0], thread: [34,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [524,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [524,0,0], thread: [36,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [524,0,0], thread: [37,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

Traceback (most recent call last):
  File "play_with_glue.py", line 43, in <module>
    }[config.mode]()
  File "dne/awesome_glue/task.py", line 420, in attack
    self.evaluate_predictor()
  File "env_dne/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "dne/awesome_glue/task.py", line 334, in evaluate_predictor
    outputs = self.predictor.predict_batch_instance(instances)
  File "dne/allennlpx/predictors/predictor.py", line 197, in predict_batch_instance
    results = self.predict_batch_json(json_dicts)
  File "dne/allennlpx/predictors/predictor.py", line 124, in predict_batch_json
    outputs = self._model.forward_on_instances(b_en_insts)
  File "env_dne/lib/python3.6/site-packages/allennlp/models/model.py", line 158, in forward_on_instances
    outputs = self.make_output_human_readable(self(**model_input))
  File "env_dne/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "dne/awesome_glue/bert_classifier.py", line 30, in forward
    mask=sent['tokens']['mask'])
  File "env_dne/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "env_dne/lib/python3.6/site-packages/allennlp/modules/token_embedders/pretrained_transformer_embedder.py", line 120, in forward
    embeddings = self.transformer_model(**parameters)[0]
  File "env_dne/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "env_dne/lib/python3.6/site-packages/transformers/modeling_bert.py", line 799, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "env_dne/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "env_dne/lib/python3.6/site-packages/transformers/modeling_bert.py", line 189, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "env_dne/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "dne/awesome_glue/weighted_embedding.py", line 44, in forward
    nbr_tokens, _coeff = self.hull.get_nbr_and_coeff(tokens.view(-1))
  File "dne/awesome_glue/weighted_util.py", line 60, in get_nbr_and_coeff
    nbr_num_lst = (nbr_tokens != 0).sum(dim=1).tolist()
RuntimeError: CUDA error: device-side assert **triggered**

```

Can you help me fix the error?

PS: I found that the required allennlp commit `allennlp.git@bdb29a831ed68cb948b18b42fa61646b9ec11bf8` gives segmentation fault. I tried using `allennlp.git@b41f90ec23cc43ac380b14aa314e2975d67e857d` and this worked.

Thanks,

**Comment by dugu9sword** [comment]
Hi, sorry for my late response!

Not sure what happened in your case, but I have made some modifications to the repo, including upgrading `allennlp` from an unstable version to the official release `1.2`. (well, when I attempted to run the code on my machine, it will also give Segmentation Fault...)

I run the current code on my machine (4xTitan) and it works fine.

Thanks~
